# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0/raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as v0_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rv0/raft.proto\x12\tmindxv.v0\x1a\rv0/core.proto\"0\n\x0bRaftMessage\x12\x10\n\x08group_id\x18\x01 \x01(\x0c\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"7\n\x13SharedGroupProposal\x12\x12\n\nproxy_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x99\x01\n\x13SharedGroupSnapshot\x12K\n\x0fproxy_snapshots\x18\x01 \x03(\x0b\x32\x32.mindxv.v0.SharedGroupSnapshot.ProxySnapshotsEntry\x1a\x35\n\x13ProxySnapshotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32K\n\rRaftTransport\x12:\n\x07Receive\x12\x16.mindxv.v0.RaftMessage\x1a\x17.mindxv.v0.EmptyMessageB4Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v0.raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocol'
  _globals['_SHAREDGROUPSNAPSHOT_PROXYSNAPSHOTSENTRY']._options = None
  _globals['_SHAREDGROUPSNAPSHOT_PROXYSNAPSHOTSENTRY']._serialized_options = b'8\001'
  _globals['_RAFTMESSAGE']._serialized_start=43
  _globals['_RAFTMESSAGE']._serialized_end=91
  _globals['_SHAREDGROUPPROPOSAL']._serialized_start=93
  _globals['_SHAREDGROUPPROPOSAL']._serialized_end=148
  _globals['_SHAREDGROUPSNAPSHOT']._serialized_start=151
  _globals['_SHAREDGROUPSNAPSHOT']._serialized_end=304
  _globals['_SHAREDGROUPSNAPSHOT_PROXYSNAPSHOTSENTRY']._serialized_start=251
  _globals['_SHAREDGROUPSNAPSHOT_PROXYSNAPSHOTSENTRY']._serialized_end=304
  _globals['_RAFTTRANSPORT']._serialized_start=306
  _globals['_RAFTTRANSPORT']._serialized_end=381
# @@protoc_insertion_point(module_scope)
