# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import core_pb2 as v0_dot_core__pb2
from . import raft_pb2 as v0_dot_raft__pb2


class RaftTransportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Receive = channel.unary_unary(
                '/mindxv.v0.RaftTransport/Receive',
                request_serializer=v0_dot_raft__pb2.RaftMessage.SerializeToString,
                response_deserializer=v0_dot_core__pb2.EmptyMessage.FromString,
                )


class RaftTransportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Receive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftTransportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Receive': grpc.unary_unary_rpc_method_handler(
                    servicer.Receive,
                    request_deserializer=v0_dot_raft__pb2.RaftMessage.FromString,
                    response_serializer=v0_dot_core__pb2.EmptyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mindxv.v0.RaftTransport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftTransport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mindxv.v0.RaftTransport/Receive',
            v0_dot_raft__pb2.RaftMessage.SerializeToString,
            v0_dot_core__pb2.EmptyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
