// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: v0/raft.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId []byte `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_raft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v0_raft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_v0_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftMessage) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *RaftMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SharedGroupProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyName string `protobuf:"bytes,1,opt,name=proxy_name,json=proxyName,proto3" json:"proxy_name,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SharedGroupProposal) Reset() {
	*x = SharedGroupProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_raft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedGroupProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedGroupProposal) ProtoMessage() {}

func (x *SharedGroupProposal) ProtoReflect() protoreflect.Message {
	mi := &file_v0_raft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedGroupProposal.ProtoReflect.Descriptor instead.
func (*SharedGroupProposal) Descriptor() ([]byte, []int) {
	return file_v0_raft_proto_rawDescGZIP(), []int{1}
}

func (x *SharedGroupProposal) GetProxyName() string {
	if x != nil {
		return x.ProxyName
	}
	return ""
}

func (x *SharedGroupProposal) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SharedGroupSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxySnapshots map[string][]byte `protobuf:"bytes,1,rep,name=proxy_snapshots,json=proxySnapshots,proto3" json:"proxy_snapshots,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SharedGroupSnapshot) Reset() {
	*x = SharedGroupSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v0_raft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedGroupSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedGroupSnapshot) ProtoMessage() {}

func (x *SharedGroupSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_v0_raft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedGroupSnapshot.ProtoReflect.Descriptor instead.
func (*SharedGroupSnapshot) Descriptor() ([]byte, []int) {
	return file_v0_raft_proto_rawDescGZIP(), []int{2}
}

func (x *SharedGroupSnapshot) GetProxySnapshots() map[string][]byte {
	if x != nil {
		return x.ProxySnapshots
	}
	return nil
}

var File_v0_raft_proto protoreflect.FileDescriptor

var file_v0_raft_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x30, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6d, 0x69, 0x6e, 0x64, 0x78, 0x76, 0x2e, 0x76, 0x30, 0x1a, 0x0d, 0x76, 0x30, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0b, 0x52, 0x61, 0x66,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x48, 0x0a,
	0x13, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb5, 0x01, 0x0a, 0x13, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12,
	0x5b, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x78,
	0x76, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x1a, 0x41, 0x0a, 0x13,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32,
	0x4b, 0x0a, 0x0d, 0x52, 0x61, 0x66, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x69,
	0x6e, 0x64, 0x78, 0x76, 0x2e, 0x76, 0x30, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x78, 0x76, 0x2e, 0x76, 0x30, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6a, 0x79, 0x2d, 0x64,
	0x76, 0x2f, 0x6d, 0x69, 0x6e, 0x64, 0x2d, 0x78, 0x2f, 0x6d, 0x69, 0x6e, 0x64, 0x78, 0x2d, 0x76,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v0_raft_proto_rawDescOnce sync.Once
	file_v0_raft_proto_rawDescData = file_v0_raft_proto_rawDesc
)

func file_v0_raft_proto_rawDescGZIP() []byte {
	file_v0_raft_proto_rawDescOnce.Do(func() {
		file_v0_raft_proto_rawDescData = protoimpl.X.CompressGZIP(file_v0_raft_proto_rawDescData)
	})
	return file_v0_raft_proto_rawDescData
}

var file_v0_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v0_raft_proto_goTypes = []interface{}{
	(*RaftMessage)(nil),         // 0: mindxv.v0.RaftMessage
	(*SharedGroupProposal)(nil), // 1: mindxv.v0.SharedGroupProposal
	(*SharedGroupSnapshot)(nil), // 2: mindxv.v0.SharedGroupSnapshot
	nil,                         // 3: mindxv.v0.SharedGroupSnapshot.ProxySnapshotsEntry
	(*EmptyMessage)(nil),        // 4: mindxv.v0.EmptyMessage
}
var file_v0_raft_proto_depIdxs = []int32{
	3, // 0: mindxv.v0.SharedGroupSnapshot.proxy_snapshots:type_name -> mindxv.v0.SharedGroupSnapshot.ProxySnapshotsEntry
	0, // 1: mindxv.v0.RaftTransport.Receive:input_type -> mindxv.v0.RaftMessage
	4, // 2: mindxv.v0.RaftTransport.Receive:output_type -> mindxv.v0.EmptyMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v0_raft_proto_init() }
func file_v0_raft_proto_init() {
	if File_v0_raft_proto != nil {
		return
	}
	file_v0_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v0_raft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_raft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedGroupProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v0_raft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedGroupSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v0_raft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v0_raft_proto_goTypes,
		DependencyIndexes: file_v0_raft_proto_depIdxs,
		MessageInfos:      file_v0_raft_proto_msgTypes,
	}.Build()
	File_v0_raft_proto = out.File
	file_v0_raft_proto_rawDesc = nil
	file_v0_raft_proto_goTypes = nil
	file_v0_raft_proto_depIdxs = nil
}
