# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0/cluster.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as v0_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10v0/cluster.proto\x12\tmindxv.v0\x1a\rv0/core.proto\"#\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\xc0\x01\n\x0cNodeLoadInfo\x12\x0e\n\x06uptime\x18\x01 \x01(\x04\x12\x11\n\tcpu_load1\x18\x02 \x01(\x01\x12\x11\n\tcpu_load5\x18\x03 \x01(\x01\x12\x12\n\ncpu_load15\x18\x04 \x01(\x01\x12\x11\n\tmem_total\x18\x05 \x01(\x04\x12\x15\n\rmem_available\x18\x06 \x01(\x04\x12\x10\n\x08mem_used\x18\x07 \x01(\x04\x12\x10\n\x08mem_free\x18\x08 \x01(\x04\x12\x18\n\x10mem_used_percent\x18\t \x01(\x01\x32\xec\x01\n\x0cNodesManager\x12\x37\n\tListNodes\x12\x17.mindxv.v0.EmptyMessage\x1a\x0f.mindxv.v0.Node0\x01\x12-\n\x07\x41\x64\x64Node\x12\x0f.mindxv.v0.Node\x1a\x0f.mindxv.v0.Node0\x01\x12\x36\n\nRemoveNode\x12\x0f.mindxv.v0.Node\x1a\x17.mindxv.v0.EmptyMessage\x12<\n\x08LoadInfo\x12\x17.mindxv.v0.EmptyMessage\x1a\x17.mindxv.v0.NodeLoadInfoB4Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v0.cluster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocol'
  _globals['_NODE']._serialized_start=46
  _globals['_NODE']._serialized_end=81
  _globals['_NODELOADINFO']._serialized_start=84
  _globals['_NODELOADINFO']._serialized_end=276
  _globals['_NODESMANAGER']._serialized_start=279
  _globals['_NODESMANAGER']._serialized_end=515
# @@protoc_insertion_point(module_scope)
