# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0/core.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rv0/core.proto\x12\tmindxv.v0\"\x0e\n\x0c\x45mptyMessage\"\x19\n\x0bUUIDRequest\x12\n\n\x02id\x18\x01 \x01(\x0c\x42\x34Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v0.core_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocol'
  _globals['_EMPTYMESSAGE']._serialized_start=28
  _globals['_EMPTYMESSAGE']._serialized_end=42
  _globals['_UUIDREQUEST']._serialized_start=44
  _globals['_UUIDREQUEST']._serialized_end=69
# @@protoc_insertion_point(module_scope)
