# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0/search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as v0_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv0/search.proto\x12\tmindxv.v0\x1a\rv0/core.proto\"=\n\rSearchRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\x0c\x12\r\n\x05query\x18\x02 \x03(\x02\x12\t\n\x01k\x18\x03 \x01(\r\"^\n\x17SearchPartitionsRequest\x12\x12\n\ndataset_id\x18\x01 \x01(\x0c\x12\x15\n\rpartition_ids\x18\x02 \x03(\x0c\x12\r\n\x05query\x18\x03 \x03(\x02\x12\t\n\x01k\x18\x04 \x01(\r\"\x9b\x01\n\x10SearchResultItem\x12\n\n\x02id\x18\x01 \x01(\x0c\x12;\n\x08metadata\x18\x02 \x03(\x0b\x32).mindxv.v0.SearchResultItem.MetadataEntry\x12\r\n\x05score\x18\x03 \x01(\x02\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa2\x01\n\x06Search\x12\x41\n\x06Search\x12\x18.mindxv.v0.SearchRequest\x1a\x1b.mindxv.v0.SearchResultItem0\x01\x12U\n\x10SearchPartitions\x12\".mindxv.v0.SearchPartitionsRequest\x1a\x1b.mindxv.v0.SearchResultItem0\x01\x42\x34Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v0.search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/sjy-dv/mind-x/mindx-v/protobuf;protocol'
  _globals['_SEARCHRESULTITEM_METADATAENTRY']._options = None
  _globals['_SEARCHRESULTITEM_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=45
  _globals['_SEARCHREQUEST']._serialized_end=106
  _globals['_SEARCHPARTITIONSREQUEST']._serialized_start=108
  _globals['_SEARCHPARTITIONSREQUEST']._serialized_end=202
  _globals['_SEARCHRESULTITEM']._serialized_start=205
  _globals['_SEARCHRESULTITEM']._serialized_end=360
  _globals['_SEARCHRESULTITEM_METADATAENTRY']._serialized_start=313
  _globals['_SEARCHRESULTITEM_METADATAENTRY']._serialized_end=360
  _globals['_SEARCH']._serialized_start=363
  _globals['_SEARCH']._serialized_end=525
# @@protoc_insertion_point(module_scope)
