[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "mvd"
requires-python = ">=3.8"
dynamic = ["version"]

[project.urls]
repository = "https://github.com/mind-x/mvd"

[tool.maturin]
python-source = "py"
features = ["pyo3/extension-module", "py"]
